In [4]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [17]:
scaler = MinMaxScaler()
df = pd.read_csv("Titanic.csv")
df[[ "Age", "Fare" ]].describe()

              Age        Fare
count  332.000000  417.000000
mean    30.272590   35.627188
std     14.181209   55.907576
min      0.170000    0.000000
25%     21.000000    7.895800
50%     27.000000   14.454200
75%     39.000000   31.500000
max     76.000000  512.329200

In [18]:
df[["Age","Fare"]] = scaler.fit_transform(df[["Age","Fare"]])
print(df[["Age","Fare"]])

          Age      Fare
0    0.452723  0.015282
1    0.617566  0.013663
2    0.815377  0.018909
3    0.353818  0.016908
4    0.287881  0.023984
..        ...       ...
413       NaN  0.015713
414  0.512066  0.212559
415  0.505473  0.014151
416       NaN  0.015713
417       NaN  0.043640

[418 rows x 2 columns]

In [20]:
df[["Age","Fare"]].describe()

              Age        Fare
count  332.000000  417.000000
mean     0.396975    0.069540
std      0.187013    0.109124
min      0.000000    0.000000
25%      0.274693    0.015412
50%      0.353818    0.028213
75%      0.512066    0.061484
max      1.000000    1.000000

In [21]:
scaler_2 = StandardScaler()
df[["Age","Fare"]] = scaler_2.fit_transform(df[["Age","Fare"]])
print(df[["Age","Fare"]])

          Age      Fare
0    0.298549 -0.497811
1    1.181328 -0.512660
2    2.240662 -0.464532
3   -0.231118 -0.482888
4   -0.584229 -0.417971
..        ...       ...
413       NaN -0.493856
414  0.616350  1.312180
415  0.581038 -0.508183
416       NaN -0.493856
417       NaN -0.237621

[418 rows x 2 columns]

In [ ]:
df[["Age","Fare"]].mean()

Age     1.538261e-16
Fare   -1.064962e-17
dtype: float64

In [28]:
df[["Age","Fare"]].std()

Age     1.001509
Fare    1.001201
dtype: float64

In [29]:
q1 = df["Fare"].quantile(0.25)
q3 = df["Fare"].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
print(f"Q1 = {q1:.2f}, Q3 = {q3:.2f}, IQR = {iqr:.2f}")

Q1 = -0.50, Q3 = -0.07, IQR = 0.42

In [30]:
print(f"Lower Bound = {lower_bound:.2f}, Upper Bound = {upper_bound:.2f}")

Lower Bound = -1.13, Upper Bound = 0.56